import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/theme-provider';
import { SanityLive } from '@/sanity/lib/live';
import Header from '@/components/Header';
import { ClerkProvider } from '@clerk/nextjs';
import { frFR } from '@clerk/localizations';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function UserLayout({ children }: { children: React.ReactNode }) {
  return (
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    <ClerkProvider localization={frFR as any}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-1">{children}</main>
        </div>
      </ThemeProvider>

      <SanityLive />
    </ClerkProvider>
  );
}
